on: pull_request
name: Check Commit
env:
  GOPRIVATE: github.com/OpsHelmInc/*
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  check_commit:
    name: Check Commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: 'latest'
        args: --timeout=5m
